# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


jobs:
  myjob:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run: 
          name: on error
          command: echo "it failed"
          when: on_fail
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - myjob
